# Homework 7


**Concepts covered:**

numpy arrays, array element access, basic descriptive statistics, initializing arrays, numpy functions and methods.  


**Instructions:**

Be sure to run each code block after you edit it to make sure it runs as expected. When you are done, we strongly recommend you run all the code from scratch (Runtime menu -> Restart and Run all) to make sure your current code works for all problems.

If your code raises an exception when run from scratch, it will interfere with the auto-grader process causing you to lose some or all points for this homework. Please ask for help on Piazza, attend office hours or schedule an appointment with your learning facilitator if you get stuck.


**Warning about AI:**

While we encourage you to use AI to generate practice problems, **we recommend against using generative AI in the strongest terms** to solve any part of this assignment. The goal of this assignment is for you to learn these concepts, and while using AI may help you obtain solutions to these problems, you will cheat yourself out of the learning that comes from working through the problems yourself.

**Sample Output:**

For each problem description, a sample output has been included to show what the expected output should be.


**Docstrings and Comments:**

Include a *documentation string* (docstring) for each function definition, as well as comments in the body of your code to explain each control structures (e.g., decision, loop), function call, or formula.

**Review Problem 1**

**Concept:** *List data type, list comprehension.*

**Task:**

Write a function `stdev(values)` that takes a 1D Python list of numbers and returns the population standard deviation.

**Sample Output:**


```
stdev([1, 2, 3]) should return approximately 0.8164965809

stdev([5, 5, 5, 5]) should return 0.0
```


In [1]:
# TO DO: WRITE YOUR SOLUTION HERE
def all_num_identical (values):
    '''Check all number in the list are identical'''
    for i in values:
        if i != values[0]:
            return False
    return True
def stdev(values):
    '''Returns the population standard deviation'''
    if all_num_identical(values) == True:
        return 0.0
    else:
        s = 0
        mean = sum(values)/len(values)
        for i in values:
            s += (i-mean)**2
        std= (s/len(values))**(1/2)
        return std
    
    
    
    


In [2]:
# TO DO: WRITE YOUR TEST CASES HERE
#stdev([3, 5, 9])
stdev([1,2,3])
stdev([5,5,5,5])

0.0

**Review Problem 2**

**Concept:** *List element access.*

**Task:**

Write a function `sum_list(a, b)` that takes two same-length 1D lists and returns a new list containing the element-wise sums.

If the lengths differ, print a message indicating incompatible lengths in this format: Incompatible lengths: {len(a)} vs {len(b)}.
Use list comprehension for this, not numpy.

**Sample Output:**

```
sum_list([2, 4, 6], [1, 3, 5]) → [3, 7, 11]
```


In [83]:
# TO DO: WRITE YOUR SOLUTION HERE
def sum_list(a,b):
    '''Takes 2 same-length and returns a new list containing the element-wise sums'''
    if len(a) != len(b):
        print(f'Incompatible lengths:{len(a)} vs {len(b)}')
        return None
    else:
        newlist = []
        for i in range(len(a)):
            newlist.append(a[i]+b[i])
        return newlist

Test cases for problem 2

In [78]:
# TO DO: WRITE YOUR TEST CASES HERE
sum_list([2,4,6], [1,3,5])


[3, 7, 11]

The following starter code will be used in several problems. Run the following cell before continuing.

In [5]:
# STARTER CODE TO DEFINE SOME NUMPY ARRAYS:
import numpy as np

a = np.arange(12)
b = np.array([i * 2 for i in range(1,13)])
c = np.random.randint(0, 10, 12)
print(f'a = {a}')
print(f'b = {b}')
print(f'c = {c}')



a = [ 0  1  2  3  4  5  6  7  8  9 10 11]
b = [ 2  4  6  8 10 12 14 16 18 20 22 24]
c = [7 6 6 8 8 9 6 7 1 4 6 4]


**Problem 3**

**Concept:** *Array operations.*

**Task:**

Using the arrays a, b, c defined in the starter code:

a.   Compute sum of arrays `a` plus `b`, and store the result in the variable `x`.

b.   Compute the product of arrays `a` and `b`, and store the result in the variable `y`.

c.   Compute the dot product of arrays `a` and `b`, and store the result in the variable `z`.

d.   Re-shape the array `x` as a 2x6 array, and store the result in the variable `q`.

e.   Re-shape the array `y` as a 6x2 array, and store the result in the variable `r`.

f.   Compute the dot product of arrays `q` and `r`, and store the result in the varaible `s`.

Print `x`, `y`, `z`, `q`, `r`, `s` as you go to check your work.

**Sample Output:**

```
x = [ 3  7 11 15 19 23 27 31 35 39 43 47]
y = [  0   6  18  36  60  90 126 168 216 270 330 396]
z = 2184

q =
[[ 3  7 11 15 19 23]
 [27 31 35 39 43 47]]

r =
[[  0   6]
 [ 18  36]
 [ 60  90]
 [126 168]
 [216 270]
 [330 396]]

s =
[[15660 20484]
 [37476 49020]]

```


In [6]:
# TO DO: WRITE YOUR SOLUTION HERE
x= a+b
y =a*b
z= np.dot(a,b)
q = x.reshape(2,6)
r= y.reshape(6,2)
s = np.dot(q,r)



In [7]:
#test
print(f'x= {x}')
print(f'y= {y}')
print(f'z= {z}')
print(f'q= {q}')
print(f'r= {r}')
print(f's={s}')


x= [ 2  5  8 11 14 17 20 23 26 29 32 35]
y= [  0   4  12  24  40  60  84 112 144 180 220 264]
z= 1144
q= [[ 2  5  8 11 14 17]
 [20 23 26 29 32 35]]
r= [[  0   4]
 [ 12  24]
 [ 40  60]
 [ 84 112]
 [144 180]
 [220 264]]
s=[[ 7060  8848]
 [16060 20440]]


**Problem 4**

**Concept:** *Array operations, iteration with loop, numpy functions and methods.*

**Task:**

Write a function `mean_rowwise(x)` that takes a 2D numpy array and returns a 2D column vector containing the mean of each row.

**Numeric Example:**

If `x = [[1,2,3],[10,0,-10]]`, the row means are `[[2.],[0.]]`.


**Example Function Call:**

```
mean_rowwise(np.array([[0.2, 0.3, 0.4]])) returns [[0.3]]
```




In [8]:
# TO DO: WRITE YOUR SOLUTION HERE
def mean_rowwise(x):
    '''Returns 2D column vector containing the mean of each row'''
    return np.mean(x,axis=1, keepdims=True)
    
    
    


Test cases for problem 4

In [9]:
# TO DO: WRITE YOUR TEST CASES HERE
t= [[1,2,3], [10,0,-10]]
print(mean_rowwise(np.array([[0.2,0.3,0.4]])))



[[0.3]]


**Problem 5**

**Concept:** *Array operations, iteration with loop, boolean values, numpy functions and methods.*

**Task:**

Write a function `check_row_sum(x)` that returns `True` if every row in a 2D numpy array sums to 1.0 (tolerance: between `0.999` and `1.001`), otherwise return `False`.

**Example Function Calls:**

`check_row_sum([[0.2,0.8],[0.5,0.5]])` returns `True`

`check_row_sum([[0.0, 1.0], [0.9999, 0.0012]])` returns `False`
```



In [10]:
# TO DO: WRITE YOUR SOLUTION HERE
def check_row_sum(x):
    '''Returns True if every row in 2D numpy array sums to 1.0, otherwise return False'''
    a= np.sum(x, axis = 1)
    for i in a:
        if i !=1.0: 
            return False      
    return True
    


Test cases for problem 5

In [11]:
# TO DO: WRITE YOUR TEST CASES HERE
print(check_row_sum([[0.0,1.0],[0.9999,0.0012]]))
print(check_row_sum([[0.2,0.8],[0.5,0.5]]))



False
True


**Problem 6**

**Concept:** *Array operations, numpy functions and methods.*

**Task:**

Write a function `softmax(z)` that takes in a 1D numpy array of values $z_i$, and returns an array composed of $\frac{e^{z_i}}{\sum e^{z_i}}$.

The output array shape should be the same as the input array shape.

This formula is the [softmax](https://en.wikipedia.org/wiki/Softmax_function) formula used to adjust raw machine learning outputs into more suitable probability estimates.

**Example Function Calls:**

`softmax(np.array([0,0]))` returns `np.array([0.5, 0.5])`

`softmax(np.array([-1, 0, 1]))` returns `np.array([0.09003057 0.24472847 0.66524096])`


In [12]:
# TO DO: WRITE YOUR SOLUTION HERE
def softmax(z):
    '''Returns an array composed of e^z/sum e^z'''
    ex= np.exp(z)
    sum_ex= np.sum(ex)
    new= ex/sum_ex
    return new


Test cases for problem 6

In [13]:
# TO DO: WRITE YOUR TEST CASES HERE
softmax(np.array([0,0]))
softmax(np.array([-1,0,1]))


array([0.09003057, 0.24472847, 0.66524096])

**Problem 7**

**Concept:** *Array operations.*

**Task:**
Write `softmax_2d(z)` that applies softmax row-by-row to a 2D numpy array, returning an array of the same shape.

**Example Function Calls:**

`softmax_2d(np.array([[0,0],[1,1]]))` returns `np.array([[0.5,0.5],[0.5,0.5]])`


In [14]:
# TO DO: WRITE YOUR SOLUTION HERE
def softmax_2d(z):
    '''Applies softmax row-by-row to 2D numpy array, 
        returning an array of the same shape'''
    ex= np.exp(z)
    sum_ex= np.sum(ex, axis =1, keepdims = True)
    new= ex/sum_ex
    return new


Test cases for problem 7

In [15]:
# TO DO: WRITE YOUR TEST CASES HERE
print(softmax_2d(np.array([[0,0],[1,1]])))



[[0.5 0.5]
 [0.5 0.5]]


**Problem 8**

**Concept:** *Descriptive statistics, row-wise operations, numpy functions and methods.*

**Task:**

Write `three_stats(x)` that takes an `n x k` array and returns an 3 by N array of:

1. row minimums

2. row medians

3. row maximums


**Hint:**
You can use np.min, np.median, np.max

**Example Function Calls:**

`three_stats(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]]))`
returns
`np.array([[1. 4. 7.], [2. 5. 8.], [3. 6. 9.]])`



In [16]:
# TO DO: WRITE YOUR SOLUTION HERE
def three_stats(x):
    '''Take nxk array and returns an 3 by N array of: 
        row minimums, row medians, row maximums'''
    min= np.min(x, axis =1)
    med= np.median(x,axis=1)
    max= np.max(x,axis=1)
    return np.array([min,med,max])


Test cases for problem 8

In [17]:
# TO DO: WRITE YOUR TEST CASES HERE
three_stats(np.array([[1,2,3], [4,5,6],[7,8,9]]))

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

**Problem 9**

**Concept:** *Row-wise operations, numpy functions and methods.*

**Task:**
Write `max_row_sum(a)` that takes a 2D numpy array and returns the largest row sum.

**Numeric Example:**

```[[1,2],[10,-1],[0,0]] row sums [3,9,0] → returns 9```

**Example Function Call:**

`max_row_sum(np.array([[1, 2, 3], [9, 9, 9], [1000, 100, 900]]))` returns `2000`




In [18]:
# TO DO: WRITE YOUR SOLUTION HERE
def max_row_sum(a):
    '''Takes 2D numpy array and returns the largest row sum'''
    sum = np.sum(a, axis=1, keepdims = True)
    max= np.max(sum)
    return max


Test cases for problem 9

In [19]:
# TO DO: WRITE YOUR TEST CASES HERE
max_row_sum(np.array([[1,2,3],[9,9,9],[1000,100,900]]))

np.int64(2000)

**Problem 10**

**Concept:** *Array operations; thinking about dimensions and element access.*

**Task:**

Write the function `array_init_parameters(a)` that returns either:

*  if all elements are the same and the array `a` can be recreated using `np.full((w, h), v)`, return the tuple `(w, h, v)` corresponding to (width, height, value)

* otherwise return `None`

**Numeric Example:**

```[[7,7],[7,7]] → (2,2,7)```

```[[7,7],[7,8]] → None```



In [80]:
# TO DO: WRITE YOUR SOLUTION HERE
def array_init_parameters(a):
    '''Returns the tuple (width,height,value) if all element are the same and the array a an be recreated using np.full((w,h),v)'''
    v = a[0][0]
    a= np.array(a)
    w=a.shape[1]
    h=a.shape[0]
    if np.all(a==v) :
        return (w,h,v)
    return None
        


Test cases for problem 10

In [81]:
array_init_parameters([[7,7],[7,7]])
array_init_parameters([[7,7],[7,8]])

**Problem 11**

**Concept:** *Array operations; thinking about dimensions and element access.*

**Task:**

[Kakuro](https://en.wikipedia.org/wiki/Kakuro) is a logic puzzle where the goal is to fill in numbers so that the rows and columns add up to specified numbers.

Write `kakuro_test(a, row_sums, column_sums)` that returns `True` if:

* each row sum matches `row_sums`

* each column sum matches `column_sums`

* Otherwise return `False`.

**Numeric Example:**

For the input
`kakuro_test(np.array([[7, 2], [3, 4]]), [9, 7], [10, 6])`

The row sums are 7+2=9 and 3+4=7, which matches the third element `[9, 7]`

The column sums are 7+3=10 and 2+4=6, which matches the fourth element `[10, 6]`

So this should return `True`



In [39]:
# TO DO: WRITE YOUR SOLUTION HERE
def kakuro_test(a, row_sums, column_sums):
    '''Returns True if each row matchees row_sums, and each column sum matches column_sums'''
    sum_a1 = np.sum(a,axis=1)
    sum_a0 = np.sum(a,axis=0)
    if np.all(sum_a1== row_sums) and np.all(sum_a0 == column_sums):
        return True
    return False
        


Test cases for problem 11

In [40]:
# TEST CASES TO TRYU

# this should return True
p11_test_1_result = kakuro_test(np.array([[0, 1, 2], [3, 4, 5]]), [3, 12], [3, 5, 7])
print(f'p11_test_1_result = {p11_test_1_result}')

# this should return False
p11_test_2_result = kakuro_test(np.array([[0, 2, 4], [3, 4, 5]]), [3, 12], [3, 5, 7])
print(f'p11_test_2_result = {p11_test_2_result}')



p11_test_1_result = True
p11_test_2_result = False


**Problem 12**

**Concept:** *File reading, parsing data values, array creation.*

**Task:**
Write the function `read_csv_to_array(filename)` that reads a CSV file, discards the header row, converts each element to a floating-point number, and returns a 2D numpy array.

**Sample Output:**

If file contains:

```
foo,bar
2,4
6,8
```

The function should return:
```
np.array([[2. 4.][6. 8.]])
```

In [31]:
# TO DO: WRITE YOUR SOLUTION HERE
import csv
def read_csv_to_array(filename):
    '''Reads a CSV file, discards the header row, converts each element to a floating-point number,
        and returns a 2D numpy array'''
    d= np.loadtxt(filename, skiprows=1,delimiter=',')
    return d


Test cases for problem 12

In [32]:
# TEST CASES HERE
data = read_csv_to_array("data1.csv")
print(data)


[[ 22. 183.  51.]
 [ 62. 168.  57.]
 [ 42. 150.  98.]
 [ 49. 163.  90.]
 [ 49. 129.  98.]
 [ 60. 171.  90.]
 [ 59. 181.  65.]
 [ 62. 136.  83.]
 [ 18. 144.  67.]
 [ 64. 189.  73.]]


**Problem 13**

**Concept:** *File reading, parsing data values, array creation.*


**Task:**

Write the function `get_column_stats(filename)` that a CSV file, discards the header row, and returns a 1D numpy array containing the mean of each column.

**Sample Output:**

If file contains:
```
a,b,c
1,2,3
4,5,6
```
The resulting columns means are

```np.array([2.5, 3.5, 4.5])```


In [42]:
# TO DO: WRITE YOUR SOLUTION HERE
def get_column_stats(filename):
    '''Returns a 2D numpy array containing the mean,std, min,max of each column'''
    d=np.loadtxt(filename, skiprows=1, delimiter=',')
    md= np.mean(d, axis= 0)
    sd= np.std(d, axis = 0)
    mind= np.min(d,axis = 0)
    maxd= np.max(d,axis = 0)
    return np.array([md,sd,mind,maxd])

Test cases for problem 13

In [43]:
# TEST CASES HERE
stats = get_column_stats("data1.csv")
print(stats)


[[ 48.7        161.4         77.2       ]
 [ 15.88112087  19.6936538   16.09844713]
 [ 18.         129.          51.        ]
 [ 64.         189.          98.        ]]
